import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function about() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dapp Covid Insurance Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} >
        <h1 className="d-inline-flex align-items-center mt-3" >
          Welcome to Covid Insurance DApp project UI  
        </h1>  
      </main>
    </div>
  )
}