import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dapp Covid Insurance Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} >
        <h1 className="d-inline-flex align-items-center text-white mt-3" >
          Welcome to Covid Insurance project UI  
        </h1>  
      </main>
    </div>
  )
}
